### PR TITLE
feat(docker): Modernize Hive Metastore with template-based configuration and multi-mode deployment

### PR DESCRIPTION
**Pull request by andormarkus**
# Description

This PR modernizes the Hive Metastore Docker setup by introducing template-based configuration and improving the overall build process. The changes make the Docker image more flexible for both standalone and sidecar deployment scenarios.

### Docker Build Improvements
- Added `BUILD_ENV` build argument to support two deployment modes:
  - `no_templates`: Standard mode for standalone deployment
  - `templates`: Sidecar mode with built-in configuration templates
- Upgraded to `eclipse-temurin` base image with configurable Java version
- Added multi-architecture support for Gomplate installation
- Updated dependencies to latest stable versions:
  - Hadoop 3.4.1
  - MySQL Connector 9.1.0
  - Log4j 2.24.1

### Configuration Management
- Introduced conditional template handling based on `BUILD_ENV`
- Enhanced entrypoint script with:
  - Better function organization
  - Improved error handling
  - More robust template processing
- Added comprehensive sidecar self-termination script for Kubernetes deployments

### Documentation Updates
- Added detailed build instructions for both modes
- Documented all supported environment variables
- Updated configuration examples
- Added migration guidelines

## Breaking Changes
1. Docker build process now may requires explicit `BUILD_ENV` specification
2. Base image changed to `eclipse-temurin`
3. Updated dependency versions may require configuration adjustments

@melodyyangaws

### CODE REVIEW

**Comment by melodyyangaws** [comment]
Amazing improvement Andor! thank you for the fantastic PR.

A minor change is required before the merge: 
Can you please reuse the previous Hadoop core URL in the Dockerfile ( please keep your line but comment it out for hadoop 3.4.1+) ? It ensures the backward compatibility for older Hadoop versions, such as HADOOP_VERSION=3.2.1 for EMR 6.5 ? Besides the `hadoop-xxx-lean.tar.gz` doesn't exist until the version 3.4.1. 
```
# Download and install Hadoop
RUN wget https://downloads.apache.org/hadoop/core/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}-lean.tar.gz 
```

**Comment by melodyyangaws** [comment]
please double check the .github/workflows/HMS-docker.yml , ensuring the change doesn't break the auto docker build.

**Comment by andormarkus** [comment]
Hi Melody,

I have addressed your concerns and I have made improvement accordingly. Ready for next round.

**Comment by andormarkus** [comment]
Hi Melody,

I have successfully built run it for the following Hadoop versions:
 - hadoop-3.2.4
 - hadoop-3.3.6
 - hadoop-3.4.0
 - hadoop-3.4.1


I got the following image sizes:
 - 3.2.4 - 306.86MB
 - 3.3.6 - 322.38MB
 - 3.4.0 - 333.16MB
 - 3.4.1 - 334.79MB

**Comment by melodyyangaws** [comment]
OK, it's my fault to make it complicated. Let's simplify the **Dockerfile**:

1/ To get all available Hadoop versions, use this link instead `https://archive.apache.org/dist/hadoop/core/`.  

2/ Please remove the extra layer `java-builder`. Don't worry about the AWS SDK versions. I remember Hadoop's build-in aws-java-sdk-bundle is sufficient for S3 to work in EKS, except Hadoop 3.2.1 ( the first supported version by EMR on EKS). 

We can update README to ask users to follow this **[example for Hadoop 3.2.1](https://github.com/aws-samples/hive-emr-on-eks/blob/af0b34201eeba157c7c1ae2936cdf3b9d7e2c82c/docker/Dockerfile#L39)** to replace the bundle by a newer version to meet the [IRSA requirement in EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)

3/ It's fantastic to see the reduced docker image size! Thanks for the effort, absolutely brilliant! I can see there is no big difference between the size of 3.4.0 and 3.4.1 (lean). Probably we should keep the Hadoop download link consistent, don't need the [verlte function](https://github.com/aws-samples/hive-emr-on-eks/blob/13ba1e41c394863f51081c6749ee9409c6a8b9f2/docker/Dockerfile#L95), ie. use `https://archive.apache.org/dist/hadoop/core/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz` for all versions.

4/ Since i am suggesting to remove the `java-builder` layer, the [version comparison function](https://github.com/aws-samples/hive-emr-on-eks/blob/13ba1e41c394863f51081c6749ee9409c6a8b9f2/docker/Dockerfile#L42) needs to move into `build` layer. or maybe you can think of another simpler way to tell the SDK version based on ${HADOOP_VERSION}.

**Comment by andormarkus** [comment]
Hello

1/ Updated to use the `archive.apache.org` link.

2/ The `java-builder` layer is actually necessary for optimizing image size. Let me explain why with some data comparing AWS SDK approaches:

|       | AWS SDK "minimal" | AWS SDK bundle |
|-------|--------------|----------------|
| 3.2.4 |        306MB |          471MB |
| 3.3.6 |        322MB |          592MB |
| 3.4.1 |        334MB |          802MB |

As you can see, using the full AWS SDK bundle increases image size by 165-468MB, which significantly impacts pod startup time and networking costs.

Regarding IRSA/EKS pod identity - it actually won't work even with newer AWS SDK versions. This is because the core integration is missing in Hadoop's s3a client (tracked in [Hadoop JIRA-18154](https://issues.apache.org/jira/browse/HADOOP-18154)). I tried implementing this before but ran into this limitation, I will retest it.

3/ About the image sizes: The difference between 3.4.0 and 3.4.1 is small because both use AWS SDK "minimal". For 3.4.0, I replaced the bundle with minimal SDK, while for 3.4.1 I just added the minimal SDK since it didn't come with a bundle.

4/ Since we still need the `java-builder` layer, I moved the version comparison function there (it's no longer needed in the `build` layer as we're not using lean Hadoop distribution).

**Pull request merged**
